###
POST http://localhost:6000/register
Content-Type: application/json

{
      "username":"ganesh",
      "password":"Ganesh#1995"
}
###

POST http://localhost:6000/login
Content-Type: application/json

{
      "username":"ganesh",
      "password":"Ganesh#1995"
}
###

POST http://localhost:6000/add-products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhbmVzaCIsImlhdCI6MTY5ODgzMjQ1Nn0.Fb9enJKOLaCsdmi5bNoN83ogbQoMDcp8YUta4qmQK9g

{
      "image": "https://res.cloudinary.com/dky69roxl/image/upload/v1698555761/Avatar_gdobtx.png",
      "title":"Jeans pant",
      "category":"cloths",
      "price": 500
}
###


DELETE http://localhost:6000/delete-product/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhbmVzaCIsImlhdCI6MTY5ODgzMjQ1Nn0.Fb9enJKOLaCsdmi5bNoN83ogbQoMDcp8YUta4qmQK9g
###

GET http://localhost:6000/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhbmVzaCIsImlhdCI6MTY5ODgzMjQ1Nn0.Fb9enJKOLaCsdmi5bNoN83ogbQoMDcp8YUta4qmQK9g
###
GET http://localhost:6000/products/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhbmVzaCIsImlhdCI6MTY5ODgzMjQ1Nn0.Fb9enJKOLaCsdmi5bNoN83ogbQoMDcp8YUta4qmQK9g